# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MTracker' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTracker
  pod 'SocketRocket', '~> 0.5.1'
  pod 'MBProgressHUD','0.9.2'
#  pod 'RESideMenu', '~> 4.0.7'
#  pod 'AMSlideMenu', '~> 1.5.4'
  pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git', :tag => 'v2.4.0'
  pod 'GeoJSONSerialization', '~> 0.0.4'
end
